name: broccolicutter

channels:
  - conda-forge
  - defaults

dependencies:
  - cookiecutter
  - black
  - hypothesis
  - pylint
  - pytest
  - pyyaml

# environment_variables:
#   jupyter_config_dir: "%CONDA_PREFIX%\\envs\\jjjjj\\Jupyter"